version: '3.8'
services:
  web:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./:/var/www/html"
    ports:
      - "8000:80"
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:8
    restart: always
    env_file:
      - ".env.dev"
    ports:
      - "33061:3306"
    volumes:
      - "./var/lib/mysql:/var/lib/mysql"

  php:
    build: "./etc/php/"
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www/html"
